routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', function () {
    return view('login');
});

Route::resource('/data-penduduk','WargaController');
Route::resource('/fasilitas-desa','FasilitasController');
Route::resource('/kegiatan','KegiatanController');

app/kegiatan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class kegiatan extends Model
{
    //use Notifiable;

    protected $primaryKey = 'id_kegiatan';

    protected $fillable = [
        'nama_kegiatan', 'jenis_kegiatan', 'jenis_kegiatan', 'tanggal', 'deskripsi'
    ];

    public function galeri() {
        return $this->hasMany('App\galeri');
    }
}

app/Http/Controllers/KegiatanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\kegiatan;

class KegiatanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $nkegiatan = kegiatan::paginate(20);
        return view('kegiatan.index', compact('nkegiatan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kegiatan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $kegiatan_baru = NEW kegiatan();
        $kegiatan_baru->nama_kegiatan = $request->get('nama_kegiatan');
        $kegiatan_baru->jenis_kegiatan = $request->get('jenis_kegiatan');
        $kegiatan_baru->tanggal = $request->get('tanggal');
        $kegiatan_baru->deskripsi = $request->get('deskripsi');



        $kegiatan_baru->save();

        return redirect()->route('kegiatan-desa.index')->with('status','Kegiatan baru berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id_kegiatan)
    {
        $kegiatan = kegiatan::find($id_kegiatan);
        return view('kegiatan.show',['kegiatan'=>$kegiatan]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id_kegiatan)
    {
        $kegiatan = kegiatan::find($id_kegiatan);
        return view('kegiatan.edit',['kegiatan'=>$kegiatan]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_kegiatan)
    {

        $ubah_kegiatan = kegiatan::findOrFail($id_kegiatan);
        $ubah_kegiatan->nama_kegiatan = $request->get('nama_kegiatan');
        $ubah_kegiatan->jenis_kegiatan = $request->get('jenis_kegiatan');
        $ubah_kegiatan->tanggal = $request->get('tanggal');
        $ubah_kegiatan->deskripsi = $request->get('deskripsi');

        $ubah_kegiatan->save();

        return redirect()->route('kegiatan-desa.index')->with('status','Kegiatan berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_kegiatan)
    {
        $kegiatan = kegiatan::where('id_kegiatan', $id_kegiatan)->firstOrFail();

        $kegiatan->delete();
        return redirect()->route('kegiatan-desa.index')->with('status', 'kegiatan Berhasil Dihapus');
    }
}

resources/views/kegiatan/create.blade.php
@extends('templates.home')
@section('title')
	Tambah Kegiatan
@endsection
@section('content')
<div class="container">
		<h1>Tambah Data Kegiatan</h1>
		<hr>

		<div class="card border-primary" style="max-width: 70%; margin: auto; margin-top: 40px;">

		<div class="card-header bg-primary text-white">
			<h5 class="text-light"> Tambah Data Kegiatan </h5>
		</div>

		<div class="card-body">

		<div class="container text-primary">
                <form class="form-group" action="{{ route('kegiatan.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

					<div class="row">
                        <div class="col-md-3">
                            <label class="text-primary" for="nama_kegiatan">Nama Kegiatan</label>
                        </div>
                        <div class="col-md-8">
                            <input class="form-control" type="text" name="nama_fasilitas" value="">
                            {{ ($errors->has('nama_kegiatan')) ? $errors->first('nama_kegiatan') : "" }}
                        </div>
                    </div>

                    <br>

                    <div class="row">
                        <div class="col-md-3">
                            <label class="text-primary" for="jenis_kegiatan">Jenis Kegiatan</label>
                        </div>
                        <div class="col-md-8">
                            <input class="form-control" type="text" name="jenis_kegiatan" value="">
                            {{ ($errors->has('jenis_kegiatan')) ? $errors->first('jenis_kegiatan') : "" }}
                        </div>
                    </div>
                    <br>

                    <div class="row">
                            <div class="col-md-3">
                                <label class="text-primary" for="tanggal">Tanggal</label>
                            </div>
                            <div class="col-md-8">
                                <input class="form-control" type="date" name="tanggal" value="">
                                {{ ($errors->has('tanggal')) ? $errors->first('tanggal') : "" }}
                            </div>
                    </div>

                    <br>
					<div class="row">
                        <div class="col-md-3">
                            <label class="text-primary" for="deskripsi">Deskripsi</label>
                        </div>
                        <div class="col-md-8">
                            <input class="form-control" type="text" name="deskripsi" value="">
                            {{ ($errors->has('deskripsi')) ? $errors->first('deskripsi') : "" }}
                        </div>
					</div>
                    <br>
					<div class="row">
						<div class="col-md-3 offset-md-5 offset-md-4">
							<button type="submit" class="btn btn-outline-primary">Simpan</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/kegiatan/edit.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>EDIT KEGIATAN</h1>
    <form class="form-group" action="{{ route('kegiatan.update', $kegiatan['id_kegiatan']) }}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="PATCH">
        @csrf
        <label for="nama_kegiatan">Nama Kegiatan</label>
        <input type="text" name="nama_kegiatan" value="{{ $kegiatan['nama_kegiatan'] }}"><br>

        <label for="jenis_kegiatan">Jenis Kegiatan</label>
        <input type="text" name="jenis_kegiatan" value="{{ $kegiatan['jenis_kegiatan'] }}"><br>

        <label for="tanggal">Tanggal</label>
        <input type="date" name="tanggal" value="{{ $kegiatan['tanggal'] }}"><br>

        <label for="deskripsi">Deskripsi</label>
        <input type="text" name="deskripsi" value="{{ $kegiatan['deskripsi'] }}"><br>
        <button name="button">Submit</button>
    </form>
  </body>
</html>

resources/views/kegiatan/index.blade.php
@extends('templates.home')
@section('title')
	Kegiatan
@endsection
@section('css')
	<style>
		body
        {
			padding-top: 30px;
		}

		th, td
        {
			padding: 10px;
			text-align: center;
		}

		td a
        {
			margin: 3px;
			align-content: center;
			color: white;
		}

		td a:hover
        {
			text-decoration: none;
		}

		td button
        {
			margin-top: 5px;
			cursor: pointer;
		}
	</style>
@endsection
@section('content')

<div class="container">
    <h1 class="text-light">Kegiatan</h1>
    <div class="row">
        <div class="col-md-2">
            <a class="btn btn-outline-primary bg-light" href="{{ route('kegiatan.create') }}">
                <span data-feather="plus-circle"></span> Tambah <span class="sr-only">(current)</span></a>
        </div>
    </div>
    <br>
    <div class="table-responsive">
    <table class="table table-striped">
    <thead>
        <tr class="bg-primary text-light">
                <th scope="col">Nama Kegiatan</th>
                <th scope="col">Jenis Kegiatan</th>
                <th scope="col">Tanggal</th>
                <th scope="col">Deskripsi</th>
                <th scope="col">Aksi</th>
        </tr>
    </thead>
    <tbody>
            @foreach ($nkegiatan as $kegiatan)
            <tr class="table-light">

                <td>{{ $kegiatan['nama_kegiatan'] }}</td>
                <td>{{ $kegiatan['jenis_kegiatan'] }}</td>
                <td>{{ $kegiatan['tanggal'] }}</td>
                <td>{{ $kegiatan['deskripsi'] }}</td>
                <td>
                        <a class="btn-sm btn-primary" href="{{ route('kegiatan.show', ['id_kegiatan'=>$kegiatan->id_kegiatan]) }}"><span data-feather="eye"></span>Detail<span class="sr-only">(current)</span></a>
                        <a class="btn-sm btn-success d-inline" href="{{ route('kegiatan.edit', ['id_kegiatan'=>$kegiatan->id_kegiatan]) }}"><span data-feather="edit-2"></span>Edit<span class="sr-only">(current)</span></a>

                        <form class="d-inline" onsubmit="return confirm('DELETE this user permanetly?')" action="{{ route('kegiatan.destroy', ['id_kegiatan'=>$kegiatan->id_kegiatan]) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn-sm btn-danger" value="Delete" name="submit"><span data-feather="trash"></span>Delete<span class="sr-only">(current)</span></button>
                        </form>
                    </td>
            </tr>
        @endforeach
    </tbody>
    </table>

</div>
</div>
@endsection