routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', function () {
    return view('login');
});

Route::resource('/data-penduduk','WargaController');
Route::resource('/fasilitas-desa','FasilitasController');
Route::resource('/kegiatan','KegiatanController');

app/fasilitas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class fasilitas extends Model
{
    protected $primaryKey = 'id_fasilitas';

    protected $fillable = [
        'nama_fasilitas', 'deskripsi', 'lokasi'
    ];
}

app/Http/Controllers/FasilitasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\fasilitas;

class FasilitasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $nfasilitas = fasilitas::paginate(20);
        return view('fasilitas.index', compact('nfasilitas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('fasilitas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $fasilitas_baru = new fasilitas;
        $fasilitas_baru->nama_fasilitas = $request->get('nama_fasilitas');
        $fasilitas_baru->lokasi = $request->get('lokasi');
        $fasilitas_baru->deskripsi = $request->get('deskripsi');
        $fasilitas_baru->save();
        return redirect()->route('fasilitas-desa.index')->with('status', 'Fasilitas Berhasil Dibuat');
        // echo "anda berada pada method tambah";

        // return $request;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $fasilitas = fasilitas::findOrFail($id);
        return view('fasilitas.show', ['fasilitas'=>$fasilitas]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $fasilitas = fasilitas::findOrFail($id);
        return view('fasilitas.edit', ['fasilitas'=>$fasilitas]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $fasilitas_baru = fasilitas::findOrFail($id);
        $fasilitas_baru->nama_fasilitas = $request->get('nama_fasilitas');
        $fasilitas_baru->lokasi = $request->get('lokasi');
        $fasilitas_baru->deskripsi = $request->get('deskripsi');
        $fasilitas_baru->save();
        return redirect()->route('fasilitas-desa.index')->with('status', 'Fasilitas Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $fasilitas = fasilitas::findOrFail($id);
        $fasilitas->delete();

        return redirect()->route('fasilitas-desa.index')->with('status', 'Fasilitas Berhasil Dihapus');
    }
}

resources/views/fasilitas/create.blade.php
@extends('templates.home')
@section('title')
	Tambah Data Warga
@endsection
@section('content')

	<div class="container">
		<h1>Tambah Data Warga</h1>
		<hr>

		<div class="card border-primary" style="max-width: 70%; margin: auto; margin-top: 40px;">

		<div class="card-header bg-primary text-white">
			<h5 class="text-light"> Tambah Data Warga </h5>
		</div>

		<div class="card-body">

		<div class="container text-primary">
                <form class="form-group" action="{{ route('fasilitas-desa.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

					<div class="row">
                        <div class="col-md-3">
                            <label class="text-primary" for="nama_fasilitas">Nama Fasilitas</label>
                        </div>
                        <div class="col-md-8">
                            <input class="form-control" type="text" name="nama_fasilitas" value="">
                            {{ ($errors->has('nama_fasilitas')) ? $errors->first('nama_fasilitas') : "" }}
                        </div>
					</div>
                    <br>
                    <div class="row">
                        <div class="col-md-3">
                            <label class="text-primary" for="lokasi">Lokasi</label>
                        </div>
                        <div class="col-md-8">
                            <input class="form-control" type="text" name="lokasi" value="">
                            {{ ($errors->has('lokasi')) ? $errors->first('lokasi') : "" }}
                        </div>
                    </div>
                    <br>
					<div class="row">
                        <div class="col-md-3">
                            <label class="text-primary" for="deskripsi">Deskripsi</label>
                        </div>
                        <div class="col-md-8">
                            <input class="form-control" type="text" name="deskripsi" value="">
                            {{ ($errors->has('deskripsi')) ? $errors->first('deskripsi') : "" }}
                        </div>
						</div>
                    </div>
                    <br>
					<div class="row">
						<div class="col-md-3 offset-md-5 offset-md-4">
							<button type="submit" class="btn btn-outline-primary">Simpan</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/fasilitas/edit.blade.php
@extends('templates.home')
@section('title')
	Ubah Data Warga
@endsection
@section('content')

	<div class="container">
		<h1>Ubah Data Fasilitas</h1>
		<hr>

		<div class="card border-primary" style="max-width: 70%; margin: auto; margin-top: 40px;">

		<div class="card-header bg-primary text-white">
			<h5 class="text-light"> Ubah Data Fasilitas Detail </h5>
		</div>

		<div class="card-body">

		<div class="container text-primary">
            <form action="{{ route('fasilitas-desa.update', ['id_fasilitas'=>$fasilitas->id_fasilitas]) }}" method="POST" class="form-group"
                enctype="multipart/form-data">

                <input name="_method" type="hidden" value="PATCH">
				@csrf
                @method('PUT')

		</div>
            <br>
					<div class="row">
                        <div class="col-md-3">
                            <label class="text-primary" for="nama_fasilitas">Nama Fasilitas</label>
                        </div>
                        <div class="col-md-8">
                            <input class="form-control" type="text" name="nama_fasilitas" value="{{ $fasilitas['nama_fasilitas'] }}">
                            {{ ($errors->has('nama_fasilitas')) ? $errors->first('nama_fasilitas') : "" }}
                        </div>
					</div>
                    <br>
                    <div class="row">
                        <div class="col-md-3">
                            <label class="text-primary" for="lokasi">Lokasi</label>
                        </div>
                        <div class="col-md-8">
                            <input class="form-control" type="text" name="lokasi" value="{{ $fasilitas['lokasi'] }}">
                            {{ ($errors->has('lokasi')) ? $errors->first('lokasi') : "" }}
                        </div>
                    </div>
                    <br>
                    <div class="row">
                            <div class="col-md-3">
                                <label class="text-primary" for="deskripsi">Deskripsi</label>
                            </div>
                            <div class="col-md-8">
                                <input class="form-control" type="text" name="deskripsi" value="{{ $fasilitas['deskripsi'] }}">
                                {{ ($errors->has('dekripsi')) ? $errors->first('deskripsi') : "" }}
                            </div>
                        </div>
                        <br>
					<div class="row">
						<div class="col-md-3 offset-md-5 offset-md-4">
							<button type="submit" class="btn btn-outline-primary">Simpan</button>
						</div>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/fasilitas/index.blade.php
@extends('templates.home')
@section('title')
	Fasilitas
@endsection
@section('css')
	<style>
		body
        {
			padding-top: 30px;
		}

		th, td
        {
			padding: 10px;
			text-align: center;
		}

		td a
        {
			margin: 3px;
			align-content: center;
			color: white;
		}

		td a:hover
        {
			text-decoration: none;
		}

		td button
        {
			margin-top: 5px;
			cursor: pointer;
		}
	</style>
@endsection
@section('content')

<div class="container">
    <h1 class="text-light">Fasilitas</h1>
    <div class="row">
        <div class="col-md-2">
            <a class="btn btn-outline-primary bg-light" href="{{ route('fasilitas-desa.create') }}">
                <span data-feather="plus-circle"></span> Tambah <span class="sr-only">(current)</span></a>
        </div>
    </div>
    <br>
    <div class="table-responsive">
    <table class="table table-striped">
    <thead>
        <tr class="bg-primary text-light">
            <th scope="col">No</th>
            <th scope="col">Nama Fasilitas</th>
            <th scope="col">Lokasi</th>
            <th scope="col">Deskripsi</th>
            <th scope="col">Aksi</th>
        </tr>
    </thead>
    <tbody>
            @foreach ($nfasilitas as $fasilitas)
            <tr class="table-light">
                <td>{{ $fasilitas['id_fasilitas'] }}</td>
                <td>{{ $fasilitas['nama_fasilitas'] }}</td>
                <td>{{ $fasilitas['lokasi'] }}</td>
                <td>{{ $fasilitas['deskripsi'] }}</td>
                <td class="table-light">
                    <a class="btn-sm btn-primary" href="{{ route('fasilitas-desa.show',$fasilitas['id_fasilitas']) }}">
                        <span data-feather="eye"></span>Detail<span class="sr-only">(current)</span></a>
                    <a class="btn-sm btn-success d-inline" href="{{ route('fasilitas-desa.edit',$fasilitas['id_fasilitas']) }}">
                        <span data-feather="edit-2"></span>Edit<span class="sr-only">(current)</span></a>
                    <form class="d-inline" onsubmit="return confirm('Delete this facility permanently?')"
                        action="{{route('fasilitas-desa.destroy', $fasilitas['id_fasilitas'])}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn-sm btn-danger" value="Delete" name="submit">
                        <span data-feather="trash"></span>Delete<span class="sr-only">(current)</span></button>
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
    </table>

</div>
</div>
@endsection

resources/views/fasilitas/show.blade.php
@extends('templates.home')
@section('title')
	Detail Fasilitas
@endsection
@section('content')

	<h1>Detail Warga</h1>
	<hr>
	<br>

	<div class="card bg-white border-info" style="max-width: 70%; margin: auto; min-height: 400px;">


		<div class="row">
			<div class="col-md-12 text-center">
				<h3>No = {{ $fasilitas->id_fasilitas }} </h3>
			</div>
		</div>
		<hr>
		<br>
		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				Nama Fasilitas
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $fasilitas->nama_fasilitas }}
			</div>
			<br>
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				Lokasi
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $fasilitas->lokasi }}
			</div>
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				Deskripsi
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $fasilitas->deskripsi }}
			</div>
        </div>
	</div>

@endsection