routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', function () {
    return view('login');
});

Route::resource('/data-penduduk','WargaController');
Route::resource('/fasilitas-desa','FasilitasController');
Route::resource('/kegiatan','KegiatanController');

resources/views/templates/Partials/_head.blade.php
<head>
    <meta charset="etf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{csrf_token() }}">
    <title>@yield('title')</title>

    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link rel="stylesheet" href="{{asset('css/dashboard.css')}}">
    @yield('css')
</head>

resources/views/templates/Partials/_script.blade.php
<script src="{{asset('js/app.js')}}"></script>
    <script src="{{asset('js/feather.min.js')}}"></script>
        <script>
            feather.replace()
        </script>
    @yield('js')

resources/views/templates/Partials/_sideNav.blade.php
<nav class="col-md-2 d-none d-md-block bg-dark sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-link">
                <a class="nav-item active" href="{{route('data-penduduk.index')}}">
                    <span data-feather="user"></span>
                    Warga
                </a>
            </li>
        </ul>

        <ul class="nav flex-column">
            <li class="nav-link">
                <a class="nav-item active" href="{{route('fasilitas-desa.index')}}">
                    <span data-feather="list"></span>
                    Fasilitas
                </a>
            </li>
        </ul>

        <ul class="nav flex-column">
            <li class="nav-link">
                <a class="nav-item active" href="{{route('kegiatan.index')}}">
                    <span data-feather="book"></span>
                    Kegiatan
                </a>
            </li>
        </ul>
    </div>
</nav>

resources/views/templates/Partials/_topNav.blade.php
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand" href="#">Desaku</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        {{-- <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-link">
                    <a class="nav-link" href="{{route('data-penduduk.index') }}">Warga</a>
                </li>
            </ul>

            <form class="form-inline my-2 my-lg-0">
                <input type="text" placeholder="Search" aria-label="Search" class="form-control mr-sm-2">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

            <ul class="navbar-nav px-3">
                <li class="nav item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">Username</a>

                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a href="#" class="dropdown">Logout</a>
                    </div>
                </li>
            </ul>
        </div> --}}
</nav>